routes/web.php
 <?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::group(['middleware' => 'web'], function(){
   Route::get('user/profil', 'UserController@profil')->name('user.profil');
   Route::patch('user/{id}/change', 'UserController@changeProfil');

   Route::get('transaksi/baru', 'PenjualanDetailController@newSession')->name('transaksi.new');
   Route::get('transaksi/{id}/data', 'PenjualanDetailController@listData')->name('transaksi.data');
   Route::get('transaksi/cetaknota', 'PenjualanDetailController@printNota')->name('transaksi.cetak');
   Route::get('transaksi/notapdf', 'PenjualanDetailController@notaPDF')->name('transaksi.pdf');
   Route::post('transaksi/simpan', 'PenjualanDetailController@saveData');
   Route::get('transaksi/loadform/{diskon}/{total}/{diterima}', 'PenjualanDetailController@loadForm');
   Route::resource('transaksi', 'PenjualanDetailController');
});

Route::group(['middleware' => ['web', 'cekuser:1' ]], function(){
   Route::get('kategori/data', 'KategoriController@listData')->name('kategori.data');
   Route::resource('kategori', 'KategoriController');

   Route::get('produk/data', 'ProdukController@listData')->name('produk.data');
   Route::post('produk/hapus', 'ProdukController@deleteSelected');
   Route::post('produk/cetak', 'ProdukController@printBarcode');
   Route::resource('produk', 'ProdukController');

   Route::get('supplier/data', 'SupplierController@listData')->name('supplier.data');
   Route::resource('supplier', 'SupplierController');

   Route::get('member/data', 'MemberController@listData')->name('member.data');
   Route::post('member/cetak', 'MemberController@printCard');
   Route::resource('member', 'MemberController');

   Route::get('pengeluaran/data', 'PengeluaranController@listData')->name('pengeluaran.data');
   Route::resource('pengeluaran', 'PengeluaranController');


   Route::get('user/data', 'UserController@listData')->name('user.data');
   Route::resource('user', 'UserController');

   Route::get('pembelian/data', 'PembelianController@listData')->name('pembelian.data');
   Route::get('pembelian/{id}/tambah', 'PembelianController@create');
   Route::get('pembelian/{id}/lihat', 'PembelianController@show');
   Route::resource('pembelian', 'PembelianController');   

   Route::get('pembelian_detail/{id}/data', 'PembelianDetailController@listData')->name('pembelian_detail.data');
   Route::get('pembelian_detail/loadform/{diskon}/{total}', 'PembelianDetailController@loadForm');
   Route::resource('pembelian_detail', 'PembelianDetailController');   

   Route::get('penjualan/data', 'PenjualanController@listData')->name('penjualan.data');
   Route::get('penjualan/{id}/lihat', 'PenjualanController@show');
   Route::resource('penjualan', 'PenjualanController');

   Route::get('laporan', 'LaporanController@index')->name('laporan.index');
   Route::post('laporan', 'LaporanController@refresh')->name('laporan.refresh');
   Route::get('laporan/data/{awal}/{akhir}', 'LaporanController@listData')->name('laporan.data'); 
   Route::get('laporan/pdf/{awal}/{akhir}', 'LaporanController@exportPDF');

   Route::resource('setting', 'SettingController');
});

app/PenjualanDetail.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PenjualanDetail extends Model
{
    protected $table = 'penjualan_detail';
	protected $primaryKey = 'id_penjualan_detail';
}

app/Http/Controllers/PenjualanDetailController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Redirect;
use Auth;
use PDF;
use App\Penjualan;
use App\Produk;
use App\Member;
use App\Setting;
use App\PenjualanDetail;

class PenjualanDetailController extends Controller
{
   public function index()
   {
      $produk = Produk::all();
      $member = Member::all();
      $setting = Setting::first();

      if (!empty(session('idpenjualan'))) {
         $idpenjualan = session('idpenjualan');
         return view('penjualan_detail.index', compact('produk', 'member', 'setting', 'idpenjualan'));
      } else {
         return Redirect::route('home');
      }
   }

   public function listData($id)
   {

      $detail = PenjualanDetail::leftJoin('produk', 'produk.kode_produk', '=', 'penjualan_detail.kode_produk')
         ->where('id_penjualan', '=', $id)
         ->get();
      $no = 0;
      $data = array();
      $total = 0;
      $total_item = 0;
      foreach ($detail as $list) {
         $no++;
         $row = array();
         $row[] = $no;
         $row[] = $list->kode_produk;
         $row[] = $list->nama_produk;
         $row[] = "Rp. " . format_uang($list->harga_jual);
         $row[] = "<input type='number' class='form-control' name='jumlah_$list->id_penjualan_detail' value='$list->jumlah' onChange='changeCount($list->id_penjualan_detail)'>";
         $row[] = $list->diskon . "%";
         $row[] = "Rp. " . format_uang($list->sub_total);
         $row[] = '<div class="btn-group">
               <a onclick="deleteItem(' . $list->id_penjualan_detail . ')" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a>';
         $data[] = $row;

         $total += $list->harga_jual * $list->jumlah;
         $total_item += $list->jumlah;
      }

      $data[] = array("<span class='hide total'>$total</span><span class='hide totalitem'>$total_item</span>", "", "", "", "", "", "", "");

      $output = array("data" => $data);
      return response()->json($output);
   }

   public function store(Request $request)
   {
      $produk = Produk::where('kode_produk', '=', $request['kode'])->first();

      $detail = new PenjualanDetail;
      $detail->id_penjualan = $request['idpenjualan'];
      $detail->kode_produk = $request['kode'];
      $detail->harga_jual = $produk->harga_jual;
      $detail->jumlah = 1;
      $detail->diskon = $produk->diskon;
      $detail->sub_total = $produk->harga_jual - ($produk->diskon / 100 * $produk->harga_jual);
      $detail->save();
   }

   public function update(Request $request, $id)
   {
      $nama_input = "jumlah_" . $id;
      $detail = PenjualanDetail::find($id);
      $total_harga = $request[$nama_input] * $detail->harga_jual;

      $detail->jumlah = $request[$nama_input];
      $detail->sub_total = $total_harga - ($detail->diskon / 100 * $total_harga);
      $detail->update();
   }

   public function destroy($id)
   {
      $detail = PenjualanDetail::find($id);
      $detail->delete();
   }

   public function newSession()
   {
      $penjualan = new Penjualan;
      $penjualan->kode_member = 0;
      $penjualan->total_item = 0;
      $penjualan->total_harga = 0;
      $penjualan->diskon = 0;
      $penjualan->bayar = 0;
      $penjualan->diterima = 0;
      $penjualan->id_user = Auth::user()->id;
      $penjualan->save();

      session(['idpenjualan' => $penjualan->id_penjualan]);

      return Redirect::route('transaksi.index');
   }

   public function saveData(Request $request)
   {
      $penjualan = Penjualan::find($request['idpenjualan']);
      $penjualan->kode_member = $request['member'];
      $penjualan->total_item = $request['totalitem'];
      $penjualan->total_harga = $request['total'];
      $penjualan->diskon = $request['diskon'];
      $penjualan->bayar = $request['bayar'];
      $penjualan->diterima = $request['diterima'];
      $penjualan->update();

      $detail = PenjualanDetail::where('id_penjualan', '=', $request['idpenjualan'])->get();
      foreach ($detail as $data) {
         $produk = Produk::where('kode_produk', '=', $data->kode_produk)->first();
         $produk->stok -= $data->jumlah;
         $produk->update();
      }
      return Redirect::route('transaksi.cetak');
   }

   public function loadForm($diskon, $total, $diterima)
   {
      $bayar = $total - ($diskon / 100 * $total);
      $kembali = ($diterima != 0) ? $diterima - $bayar : 0;

      $data = array(
         "totalrp" => format_uang($total),
         "bayar" => $bayar,
         "bayarrp" => format_uang($bayar),
         "terbilang" => ucwords(terbilang($bayar)) . " Rupiah",
         "kembalirp" => format_uang($kembali),
         "kembaliterbilang" => ucwords(terbilang($kembali)) . " Rupiah"
      );
      return response()->json($data);
   }

   public function printNota()
   {
      $detail = PenjualanDetail::leftJoin('produk', 'produk.kode_produk', '=', 'penjualan_detail.kode_produk')
         ->where('id_penjualan', '=', session('idpenjualan'))
         ->get();

      $penjualan = Penjualan::find(session('idpenjualan'));
      $setting = Setting::find(1);

      if ($setting->tipe_nota == 0) {
         $handle = printer_open();
         printer_start_doc($handle, "Nota");
         printer_start_page($handle);

         $font = printer_create_font("Consolas", 100, 80, 600, false, false, false, 0);
         printer_select_font($handle, $font);

         printer_draw_text($handle, $setting->nama_perusahaan, 400, 100);

         $font = printer_create_font("Consolas", 72, 48, 400, false, false, false, 0);
         printer_select_font($handle, $font);
         printer_draw_text($handle, $setting->alamat, 50, 200);

         printer_draw_text($handle, date('Y-m-d'), 0, 400);
         printer_draw_text($handle, substr("             " . Auth::user()->name, -15), 600, 400);

         printer_draw_text($handle, "No : " . substr("00000000" . $penjualan->id_penjualan, -8), 0, 500);

         printer_draw_text($handle, "============================", 0, 600);

         $y = 700;

         foreach ($detail as $list) {
            printer_draw_text($handle, $list->kode_produk . " " . $list->nama_produk, 0, $y += 100);
            printer_draw_text($handle, $list->jumlah . " x " . format_uang($list->harga_jual), 0, $y += 100);
            printer_draw_text($handle, substr("                " . format_uang($list->harga_jual * $list->jumlah), -10), 850, $y);

            if ($list->diskon != 0) {
               printer_draw_text($handle, "Diskon", 0, $y += 100);
               printer_draw_text($handle, substr("                      -" . format_uang($list->diskon / 100 * $list->sub_total), -10),  850, $y);
            }
         }

         printer_draw_text($handle, "----------------------------", 0, $y += 100);

         printer_draw_text($handle, "Total Harga: ", 0, $y += 100);
         printer_draw_text($handle, substr("           " . format_uang($penjualan->total_harga), -10), 850, $y);

         printer_draw_text($handle, "Total Item: ", 0, $y += 100);
         printer_draw_text($handle, substr("           " . $penjualan->total_item, -10), 850, $y);

         printer_draw_text($handle, "Diskon Member: ", 0, $y += 100);
         printer_draw_text($handle, substr("           " . $penjualan->diskon . "%", -10), 850, $y);

         printer_draw_text($handle, "Total Bayar: ", 0, $y += 100);
         printer_draw_text($handle, substr("            " . format_uang($penjualan->bayar), -10), 850, $y);

         printer_draw_text($handle, "Diterima: ", 0, $y += 100);
         printer_draw_text($handle, substr("            " . format_uang($penjualan->diterima), -10), 850, $y);

         printer_draw_text($handle, "Kembali: ", 0, $y += 100);
         printer_draw_text($handle, substr("            " . format_uang($penjualan->diterima - $penjualan->bayar), -10), 850, $y);


         printer_draw_text($handle, "============================", 0, $y += 100);
         printer_draw_text($handle, "-= TERIMA KASIH =-", 250, $y += 100);
         printer_delete_font($font);

         printer_end_page($handle);
         printer_end_doc($handle);
         printer_close($handle);
      }

      return view('penjualan_detail.selesai', compact('setting'));
   }

   public function notaPDF()
   {
      $detail = PenjualanDetail::leftJoin('produk', 'produk.kode_produk', '=', 'penjualan_detail.kode_produk')
         ->where('id_penjualan', '=', session('idpenjualan'))
         ->get();

      $penjualan = Penjualan::find(session('idpenjualan'));
      $setting = Setting::find(1);
      $no = 0;

      $pdf = PDF::loadView('penjualan_detail.notapdf', compact('detail', 'penjualan', 'setting', 'no'));
      $pdf->setPaper(array(0, 0, 550, 440), 'potrait');
      return $pdf->stream();
   }
}

resources/views/penjualan_detail/index.blade.php
@extends('layouts.app')

@section('title')
  Transaksi Penjualan
@endsection

@section('breadcrumb')
   @parent
   <li>penjualan</li>
   <li>tambah</li>
@endsection

@section('content')     
<div class="row">
  <div class="col-xs-12">
    <div class="box">
   
      <div class="box-body">

<form class="form form-horizontal form-produk" method="post">
{{ csrf_field() }}  
  <input type="hidden" name="idpenjualan" value="{{ $idpenjualan }}">
  <div class="form-group">
      <label for="kode" class="col-md-2 control-label">Kode Produk</label>
      <div class="col-md-5">
        <div class="input-group">
          <input id="kode" type="text" class="form-control" name="kode" autofocus required>
          <span class="input-group-btn">
            <button onclick="showProduct()" type="button" class="btn btn-info">...</button>
          </span>
        </div>
      </div>
  </div>
</form>

<form class="form-keranjang">
{{ csrf_field() }} {{ method_field('PATCH') }}
<table class="table table-striped tabel-penjualan">
<thead>
   <tr>
      <th width="30">No</th>
      <th>Kode Produk</th>
      <th>Nama Produk</th>
      <th align="right">Harga</th>
      <th>Jumlah</th>
      <th>Diskon</th>
      <th align="right">Sub Total</th>
      <th width="100">Aksi</th>
   </tr>
</thead>
<tbody></tbody>
</table>
</form>

  <div class="col-md-8">
     <div id="tampil-bayar" style="background: #dd4b39; color: #fff; font-size: 80px; text-align: center; height: 120px"></div>
     <div id="tampil-terbilang" style="background: #3c8dbc; color: #fff; font-size: 25px; padding: 10px"></div>
  </div>
  <div class="col-md-4">
    <form class="form form-horizontal form-penjualan" method="post" action="transaksi/simpan">
      {{ csrf_field() }}
      <input type="hidden" name="idpenjualan" value="{{ $idpenjualan }}">
      <input type="hidden" name="total" id="total">
      <input type="hidden" name="totalitem" id="totalitem">
      <input type="hidden" name="bayar" id="bayar">

      <div class="form-group">
        <label for="totalrp" class="col-md-4 control-label">Total</label>
        <div class="col-md-8">
          <input type="text" class="form-control" id="totalrp" readonly>
        </div>
      </div>

      <div class="form-group">
        <label for="member" class="col-md-4 control-label">Kode Member</label>
        <div class="col-md-8">
          <div class="input-group">
            <input id="member" type="text" class="form-control" name="member" value="0">
            <span class="input-group-btn">
              <button onclick="showMember()" type="button" class="btn btn-info">...</button>
            </span>
          </div>
        </div>
      </div>

      <div class="form-group">
        <label for="diskon" class="col-md-4 control-label">Diskon</label>
        <div class="col-md-8">
          <input type="text" class="form-control" name="diskon" id="diskon" value="0" readonly>
        </div>
      </div>

      <div class="form-group">
        <label for="bayarrp" class="col-md-4 control-label">Bayar</label>
        <div class="col-md-8">
          <input type="text" class="form-control" id="bayarrp" readonly>
        </div>
      </div>

      <div class="form-group">
        <label for="diterima" class="col-md-4 control-label">Diterima</label>
        <div class="col-md-8">
          <input type="number" class="form-control" value="0" name="diterima" id="diterima">
        </div>
      </div>

      <div class="form-group">
        <label for="kembali" class="col-md-4 control-label">Kembali</label>
        <div class="col-md-8">
          <input type="text" class="form-control" id="kembali" value="0" readonly>
        </div>
      </div>

    </form>
  </div>

      </div>
      
      <div class="box-footer">
        <button type="submit" class="btn btn-primary pull-right simpan"><i class="fa fa-floppy-o"></i> Simpan Transaksi</button>
      </div>
    </div>
  </div>
</div>
@include('penjualan_detail.produk')
@include('penjualan_detail.member')
@endsection

@section('script')
<script type="text/javascript">
var table;
$(function(){
  $('.tabel-produk').DataTable();

  table = $('.tabel-penjualan').DataTable({
     "dom" : 'Brt',
     "bSort" : false,
     "processing" : true,
     "ajax" : {
       "url" : "{{ route('transaksi.data', $idpenjualan) }}",
       "type" : "GET"
     }
  }).on('draw.dt', function(){
    loadForm($('#diskon').val());
  });

   $('.form-produk').on('submit', function(){
      return false;
   });

   $('body').addClass('sidebar-collapse');

   $('#kode').change(function(){
      addItem();
   });

   $('.form-keranjang').submit(function(){
     return false;
   });

   $('#member').change(function(){
      selectMember($(this).val());
   });

   $('#diterima').change(function(){
      if($(this).val() == "") $(this).val(0).select();
      loadForm($('#diskon').val(), $(this).val());
   }).focus(function(){
      $(this).select();
   });

   $('.simpan').click(function(){
      $('.form-penjualan').submit();
   });

});

function addItem(){
  $.ajax({
    url : "{{ route('transaksi.store') }}",
    type : "POST",
    data : $('.form-produk').serialize(),
    success : function(data){
      $('#kode').val('').focus();
      table.ajax.reload(function(){
         loadForm($('#diskon').val());
      });             
    },
    error : function(){
      alert("Tidak dapat menyimpan data!");
    }   
  });
}

function showProduct(){
  $('#modal-produk').modal('show');
}

function showMember(){
  $('#modal-member').modal('show');
}

function selectItem(kode){
  $('#kode').val(kode);
  $('#modal-produk').modal('hide');
  addItem();
}

function changeCount(id){
     $.ajax({
        url : "transaksi/"+id,
        type : "POST",
        data : $('.form-keranjang').serialize(),
        success : function(data){
          $('#kode').focus();
          table.ajax.reload(function(){
            loadForm($('#diskon').val());
          });             
        },
        error : function(){
          alert("Tidak dapat menyimpan data!");
        }   
     });
}

function selectMember(kode){
  $('#modal-member').modal('hide');
  $('#diskon').val('{{ $setting->diskon_member }}');
  $('#member').val(kode);
  loadForm($('#diskon').val());
  $('#diterima').val(0).focus().select();
}

function deleteItem(id){
   if(confirm("Apakah yakin data akan dihapus?")){
     $.ajax({
       url : "transaksi/"+id,
       type : "POST",
       data : {'_method' : 'DELETE', '_token' : $('meta[name=csrf-token]').attr('content')},
       success : function(data){
         table.ajax.reload(function(){
            loadForm($('#diskon').val());
          }); 
       },
       error : function(){
         alert("Tidak dapat menghapus data!");
       }
     });
   }
}

function loadForm(diskon=0, diterima=0){
  $('#total').val($('.total').text());
  $('#totalitem').val($('.totalitem').text());

  $.ajax({
       url : "transaksi/loadform/"+diskon+"/"+$('#total').val()+"/"+diterima,
       type : "GET",
       dataType : 'JSON',
       success : function(data){
         $('#totalrp').val("Rp. "+data.totalrp);
         $('#bayarrp').val("Rp. "+data.bayarrp);
         $('#bayar').val(data.bayar);
         $('#tampil-bayar').html("<small>Bayar:</small> Rp. "+data.bayarrp);
         $('#tampil-terbilang').text(data.terbilang);
        
         $('#kembali').val("Rp. "+data.kembalirp);
         if($('#diterima').val() != 0){
            $('#tampil-bayar').html("<small>Kembali:</small> Rp. "+data.kembalirp);
            $('#tampil-terbilang').text(data.kembaliterbilang);
         }
       },
       error : function(){
         alert("Tidak dapat menampilkan data!");
       }
  });
}

</script>

@endsection

resources/views/penjualan_detail/member.blade.php
<div class="modal" id="modal-member" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
   <div class="modal-dialog modal-lg">
      <div class="modal-content">
     
   <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"> &times; </span> </button>
      <h3 class="modal-title">Cari Member</h3>
   </div>
            
<div class="modal-body">
   <table class="table table-striped tabel-produk">
      <thead>
         <tr>
            <th>Kode Member</th>
            <th>Nama Member</th>
            <th>Alamat</th>
            <th>Telpon</th>
            <th>Aksi</th>
         </tr>
      </thead>
      <tbody>
         @foreach($member as $data)
         <tr>
            <th>{{ $data->kode_member }}</th>
            <th>{{ $data->nama }}</th>
            <th>{{ $data->alamat }}</th>
            <th>{{ $data->telepon }}</th>
            <th><a onclick="selectMember({{ $data->kode_member }})" class="btn btn-primary"><i class="fa fa-check-circle"></i> Pilih</a></th>
          </tr>
         @endforeach
      </tbody>
   </table>

</div>
      
         </div>
      </div>
   </div>

resources/views/penjualan_detail/notapdf.blade.php
<!DOCTYPE html>
<html>
<head>
   <title>Nota PDF</title>
   <style type="text/css">
      table td{font: arial 12px;}
      table.data td,
      table.data th{
         border: 1px solid #ccc;
         padding: 5px;
      }
      table.data th{
         text-align: center;
      }
      table.data{ border-collapse: collapse }
   </style>
</head>
<body>

<table width="100%">
  <tr>
     <td rowspan="3" width="60%"><img src="../public/images/{{$setting->logo}}" width="150"><br>
     {{ $setting->alamat }}<br><br>
     </td>
     <td>Tanggal</td>
     <td>: {{ tanggal_indonesia(date('Y-m-d')) }}</td>
  </tr>     
  <tr>
     <td>Kode Member</td>
     <td>: {{ $penjualan->kode_member }}</td>
  </tr>
</table>
         
<table width="100%" class="data">
<thead>
   <tr>
    <th>No</th>
    <th>Kode Produk</th>
    <th>Nama Produk</th>
    <th>Harga Satuan</th>
    <th>Jumlah</th>
    <th>Diskon</th>
    <th>Subtotal</th>
   </tr>

   <tbody>
    @foreach($detail as $data)
      
    <tr>
       <td>{{ ++$no }}</td>
       <td>{{ $data->kode_produk }}</td>
       <td>{{ $data->nama_produk }}</td>
       <td align="right">{{ format_uang($data->harga_jual) }}</td>
       <td>{{ $data->jumlah }}</td>
       <td align="right">{{ format_uang($data->diskon) }}%</td>
       <td align="right">{{ format_uang($data->sub_total) }}</td>
    </tr>
    @endforeach
   
   </tbody>
   <tfoot>
    <tr><td colspan="6" align="right"><b>Total Harga</b></td><td align="right"><b>{{ format_uang($penjualan->total_harga) }}</b></td></tr>
    <tr><td colspan="6" align="right"><b>Diskon</b></td><td align="right"><b>{{ format_uang($penjualan->diskon) }}%</b></td></tr>
    <tr><td colspan="6" align="right"><b>Total Bayar</b></td><td align="right"><b>{{ format_uang($penjualan->bayar) }}</b></td></tr>
    <tr><td colspan="6" align="right"><b>Diterima</b></td><td align="right"><b>{{ format_uang($penjualan->diterima) }}</b></td></tr>
    <tr><td colspan="6" align="right"><b>Kembali</b></td><td align="right"><b>{{ format_uang($penjualan->diterima - $penjualan->bayar) }}</b></td></tr>
   </tfoot>
</table>

<table width="100%">
  <tr>
    <td>
      <b>Terimakasih telah berbelanja dan sampai jumpa</b>
    </td>
    <td align="center">
      Kasir<br><br><br> {{Auth::user()->name}}
    </td>
  </tr>
</table>
</body>
</html>

resources/views/penjualan_detail/produk.blade.php
<div class="modal" id="modal-produk" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
   <div class="modal-dialog modal-lg">
      <div class="modal-content">
	  
   <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"> &times; </span> </button>
      <h3 class="modal-title">Cari Produk</h3>
   </div>
				
<div class="modal-body">
	<table class="table table-striped tabel-produk">
		<thead>
		   <tr>
		      <th>Kode Produk</th>
		      <th>Nama Produk</th>
		      <th>Harga Beli</th>
		      <th>Aksi</th>
		   </tr>
		</thead>
		<tbody>
			@foreach($produk as $data)
			<tr>
		      <th>{{ $data->kode_produk }}</th>
		      <th>{{ $data->nama_produk }}</th>
		      <th>Rp. {{ format_uang($data->harga_beli) }}</th>
		      <th><a onclick="selectItem({{ $data->kode_produk }})" class="btn btn-primary"><i class="fa fa-check-circle"></i> Pilih</a></th>
		    </tr>
			@endforeach
		</tbody>
	</table>

</div>
		
         </div>
      </div>
   </div>

resources/views/penjualan_detail/selesai.blade.php
@extends('layouts.app')

@section('title')
  Selesai Transaksi
@endsection

@section('breadcrumb')
   @parent  
   <li>Transaksi</li>
   <li>Selesai</li>
@endsection

@section('content') 
<div class="row">
  <div class="col-xs-12">
    <div class="box">
       <div class="box-body">
          <div class="alert alert-success alert-dismissible">
            <i class="icon fa fa-check"></i>
            Data Transaksi telah disimpan.
          </div>

          <br><br>
          @if($setting->tipe_nota==0)
            <a class="btn btn-warning btn-lg" href="{{ route('transaksi.cetak') }}">Cetak Ulang Nota</a>
          @else
            <a class="btn btn-warning btn-lg" onclick="tampilNota()">Cetak Ulang Nota</a>
            <script type="text/javascript">
              tampilNota();
              function tampilNota(){
                window.open("{{ route('transaksi.pdf') }}", "Nota PDF", "height=650,width=1024,left=150,scrollbars=yes");
              }              
            </script>
          @endif
          <a class="btn btn-primary btn-lg" href="{{ route('transaksi.new') }}">Transaksi Baru</a>
          <br><br><br><br>
      </div>
   </div>
  </div>
</div>
@endsection